"use client";

import { useMemo, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
  CheckCircle2,
  Target,
  Heart,
  AlertCircle,
  RotateCcw,
  X,
  Rocket,
  Copy,
  Check,
  Terminal,
  ChevronDown,
  Clipboard,
} from "lucide-react";
import { useStore } from "@/store/useStore";

function generateBuildPrompt(
  goalText: string,
  decisions: { label: string; choice: string; tradeoffs: string[] }[],
  topValues: { label: string; strength: number; description: string }[],
  blindSpots: string[],
) {
  const lines = [
    `I've just finished a structured deliberation about the following goal using Cascade (an AI decision-mapping tool). Below is the complete context of my decisions, priorities, and constraints. Help me turn this into reality.`,
    ``,
    `## Goal`,
    goalText,
    ``,
    `## Key Decisions I Made`,
    ...decisions.map(
      (d, i) =>
        `${i + 1}. **${d.label}** — I chose: "${d.choice}"${d.tradeoffs.length > 0 ? `\n   Trade-offs I accepted: ${d.tradeoffs.join("; ")}` : ""}`,
    ),
    ``,
    `## My Priorities (ranked by strength)`,
    ...topValues.map(
      (v) =>
        `- **${v.label}** (${Math.round(v.strength * 100)}% strength) — ${v.description}`,
    ),
  ];

  if (blindSpots.length > 0) {
    lines.push(
      ``,
      `## Blind Spots to Address`,
      ...blindSpots.map((bs) => `- ${bs}`),
    );
  }

  lines.push(
    ``,
    `## What I Need`,
    `Based on everything above, help me build this. Start by creating a concrete implementation plan that respects the decisions I've already made, then let's execute on it step by step. Ask me clarifying questions if anything is ambiguous.`,
  );

  return lines.join("\n");
}

function generateSummaryMarkdown(
  goalText: string,
  decisions: { label: string; choice: string }[],
  topValues: { label: string; strength: number; description: string }[],
  blindSpots: string[],
  stats: { totalNodes: number; resolved: number },
) {
  const lines = [
    `# Cascade Summary`,
    ``,
    `## Goal`,
    goalText,
    ``,
    `## Decisions Made (${decisions.length})`,
    ...decisions.map((d, i) => `${i + 1}. **${d.label}** — ${d.choice}`),
    ``,
    `## Values Revealed (${topValues.length})`,
    ...topValues.map(
      (v) =>
        `- **${v.label}** (${Math.round(v.strength * 100)}%) — ${v.description}`,
    ),
  ];

  if (blindSpots.length > 0) {
    lines.push(
      ``,
      `## Blind Spots`,
      ...blindSpots.map((bs) => `- ${bs}`),
    );
  }

  lines.push(
    ``,
    `## Stats`,
    `- Nodes explored: ${stats.totalNodes}`,
    `- Judgments resolved: ${stats.resolved}`,
    ``,
    `---`,
    `*Generated by Cascade — AI maps the terrain, you choose the path.*`,
  );

  return lines.join("\n");
}

export default function ReckoningSummary() {
  const {
    nodes,
    values,
    goalText,
    summaryDismissed,
    setSummaryDismissed,
    toggleValuePanel,
    reset,
  } = useStore();

  const [showBuildPrompt, setShowBuildPrompt] = useState(false);
  const [copiedBuild, setCopiedBuild] = useState(false);
  const [copiedSummary, setCopiedSummary] = useState(false);

  const nodeList = Object.values(nodes);

  const stats = useMemo(() => {
    const judgmentNodes = nodeList.filter(
      (n) =>
        n.type === "resolved" ||
        (n.type === "judgment" && n.status !== "resolved"),
    );
    const resolvedNodes = nodeList.filter((n) => n.type === "resolved");
    const pendingJudgments = nodeList.filter(
      (n) => n.type === "judgment" && n.status !== "resolved",
    );
    const blindSpots = nodeList.flatMap((n) => n.blindSpots || []);

    return {
      totalNodes: nodeList.length,
      totalJudgments: judgmentNodes.length,
      resolved: resolvedNodes.length,
      pending: pendingJudgments.length,
      blindSpots: [...new Set(blindSpots)],
      resolvedNodes,
    };
  }, [nodeList]);

  const allResolved =
    stats.pending === 0 && stats.resolved > 0 && !summaryDismissed;

  if (!allResolved) return null;

  const topValues = values
    .sort((a, b) => b.strength - a.strength)
    .slice(0, 5);

  const decisions = stats.resolvedNodes.map((n) => {
    const chosenOption = n.options?.find((o) => o.id === n.selectedOption);
    return {
      label: n.label,
      choice:
        chosenOption?.label || n.selectedOption || "Custom clarification",
      tradeoffs: chosenOption?.tradeoffs || [],
    };
  });

  const buildPrompt = generateBuildPrompt(
    goalText,
    decisions,
    topValues,
    stats.blindSpots,
  );

  const summaryMarkdown = generateSummaryMarkdown(
    goalText,
    decisions,
    topValues,
    stats.blindSpots,
    stats,
  );

  const handleCopyBuild = async () => {
    await navigator.clipboard.writeText(buildPrompt);
    setCopiedBuild(true);
    setTimeout(() => setCopiedBuild(false), 2000);
  };

  const handleCopySummary = async () => {
    await navigator.clipboard.writeText(summaryMarkdown);
    setCopiedSummary(true);
    setTimeout(() => setCopiedSummary(false), 2000);
  };

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      className="absolute inset-0 z-[60] flex items-center justify-center bg-cosmos-bg/80 backdrop-blur-sm"
    >
      <motion.div
        initial={{ scale: 0.9, opacity: 0, y: 20 }}
        animate={{ scale: 1, opacity: 1, y: 0 }}
        transition={{ delay: 0.1, duration: 0.4, type: "spring" }}
        className="w-[580px] max-h-[85vh] bg-cosmos-surface border border-cosmos-glow/30 rounded-2xl overflow-y-auto shadow-2xl"
      >
        <div className="p-8">
          {/* Header */}
          <div className="flex items-start justify-between mb-6">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-xl bg-cosmos-resolved/15 border border-cosmos-resolved/30 flex items-center justify-center">
                <CheckCircle2 className="w-5 h-5 text-cosmos-resolved" />
              </div>
              <div>
                <h2 className="text-xl font-display font-bold text-cosmos-text">
                  Cascade Complete
                </h2>
                <p className="text-xs text-cosmos-muted">
                  All judgment points have been resolved
                </p>
              </div>
            </div>
            <button
              onClick={() => setSummaryDismissed(true)}
              className="text-cosmos-muted hover:text-cosmos-text transition-colors p-1"
            >
              <X className="w-4 h-4" />
            </button>
          </div>

          {/* Goal */}
          <div className="mb-6 p-4 bg-cosmos-glow/5 border border-cosmos-glow/20 rounded-xl">
            <div className="flex items-center gap-2 mb-1.5">
              <Target className="w-3.5 h-3.5 text-cosmos-glow" />
              <span className="text-[10px] uppercase tracking-wider text-cosmos-glow font-medium">
                Your Goal
              </span>
            </div>
            <p className="text-sm text-cosmos-text">{goalText}</p>
          </div>

          {/* Stats row */}
          <div className="grid grid-cols-3 gap-3 mb-6">
            <div className="text-center p-3 bg-cosmos-bg rounded-xl border border-cosmos-border">
              <div className="text-2xl font-display font-bold text-cosmos-text">
                {stats.totalNodes}
              </div>
              <div className="text-[10px] text-cosmos-muted uppercase tracking-wider">
                Nodes explored
              </div>
            </div>
            <div className="text-center p-3 bg-cosmos-bg rounded-xl border border-cosmos-border">
              <div className="text-2xl font-display font-bold text-cosmos-resolved">
                {stats.resolved}
              </div>
              <div className="text-[10px] text-cosmos-muted uppercase tracking-wider">
                Decisions made
              </div>
            </div>
            <div className="text-center p-3 bg-cosmos-bg rounded-xl border border-cosmos-border">
              <div className="text-2xl font-display font-bold text-cosmos-glow">
                {topValues.length}
              </div>
              <div className="text-[10px] text-cosmos-muted uppercase tracking-wider">
                Values revealed
              </div>
            </div>
          </div>

          {/* Decisions */}
          <div className="mb-6">
            <h3 className="text-xs font-medium text-cosmos-resolved uppercase tracking-wider mb-3">
              Your Decisions
            </h3>
            <div className="space-y-2">
              {decisions.map((d, i) => (
                <div
                  key={i}
                  className="flex items-start gap-3 p-3 bg-cosmos-bg rounded-lg border border-cosmos-border"
                >
                  <div className="w-5 h-5 rounded-full bg-cosmos-resolved/20 flex items-center justify-center shrink-0 mt-0.5">
                    <span className="text-[10px] text-cosmos-resolved font-bold">
                      {i + 1}
                    </span>
                  </div>
                  <div className="flex-1 min-w-0">
                    <div className="text-xs font-medium text-cosmos-text">
                      {d.label}
                    </div>
                    <div className="text-xs text-cosmos-resolved/80 mt-0.5">
                      {d.choice}
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Values */}
          {topValues.length > 0 && (
            <div className="mb-6">
              <div className="flex items-center justify-between mb-3">
                <h3 className="text-xs font-medium text-cosmos-glow uppercase tracking-wider">
                  Values Revealed
                </h3>
                <button
                  onClick={() => {
                    setSummaryDismissed(true);
                    toggleValuePanel();
                  }}
                  className="text-[10px] text-cosmos-glow/60 hover:text-cosmos-glow transition-colors"
                >
                  Open full mirror
                </button>
              </div>
              <div className="space-y-2">
                {topValues.map((v) => (
                  <div
                    key={v.id}
                    className="flex items-center gap-3 p-3 bg-cosmos-bg rounded-lg border border-cosmos-border"
                  >
                    <Heart className="w-3.5 h-3.5 text-cosmos-glow shrink-0" />
                    <div className="flex-1 min-w-0">
                      <div className="text-xs font-medium text-cosmos-text">
                        {v.label}
                      </div>
                      <div className="text-[10px] text-cosmos-muted mt-0.5 line-clamp-1">
                        {v.description}
                      </div>
                    </div>
                    <div className="flex items-center gap-1.5 shrink-0">
                      <div className="w-12 h-1 bg-cosmos-border rounded-full overflow-hidden">
                        <div
                          className="h-full bg-cosmos-glow rounded-full"
                          style={{ width: `${v.strength * 100}%` }}
                        />
                      </div>
                      <span className="text-[10px] text-cosmos-muted w-7 text-right">
                        {Math.round(v.strength * 100)}%
                      </span>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Blind spots */}
          {stats.blindSpots.length > 0 && (
            <div className="mb-6">
              <h3 className="text-xs font-medium text-cosmos-conflict/80 uppercase tracking-wider mb-3">
                Blind Spots to Watch
              </h3>
              <div className="space-y-1.5">
                {stats.blindSpots.slice(0, 4).map((bs, i) => (
                  <div
                    key={i}
                    className="flex items-start gap-2 text-xs text-cosmos-muted"
                  >
                    <AlertCircle className="w-3 h-3 text-cosmos-conflict/60 mt-0.5 shrink-0" />
                    <span>{bs}</span>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Build with AI — primary CTA */}
          <div className="mb-4 p-4 bg-cosmos-glow/5 border border-cosmos-glow/30 rounded-xl">
            <div className="flex items-center justify-between mb-2">
              <div className="flex items-center gap-2">
                <Rocket className="w-4 h-4 text-cosmos-glow" />
                <h3 className="text-sm font-medium text-cosmos-text">
                  Ready to build?
                </h3>
              </div>
              <button
                onClick={() => setShowBuildPrompt(!showBuildPrompt)}
                className="text-[10px] text-cosmos-glow/60 hover:text-cosmos-glow transition-colors flex items-center gap-1"
              >
                {showBuildPrompt ? "Hide" : "Preview"} prompt
                <ChevronDown
                  className={`w-3 h-3 transition-transform duration-200 ${showBuildPrompt ? "rotate-180" : ""}`}
                />
              </button>
            </div>
            <p className="text-xs text-cosmos-muted mb-3">
              Copy a ready-made prompt with all your decisions, priorities, and
              constraints baked in. Paste it into Claude Code, Cursor, or any AI
              tool to start building.
            </p>

            <AnimatePresence>
              {showBuildPrompt && (
                <motion.div
                  initial={{ height: 0, opacity: 0 }}
                  animate={{ height: "auto", opacity: 1 }}
                  exit={{ height: 0, opacity: 0 }}
                  transition={{ duration: 0.2 }}
                  className="overflow-hidden mb-3"
                >
                  <pre className="text-[11px] text-cosmos-muted bg-cosmos-bg border border-cosmos-border rounded-lg p-3 max-h-48 overflow-y-auto whitespace-pre-wrap font-sans leading-relaxed">
                    {buildPrompt}
                  </pre>
                </motion.div>
              )}
            </AnimatePresence>

            <button
              onClick={handleCopyBuild}
              className="w-full py-3 bg-cosmos-glow/20 border border-cosmos-glow/40 rounded-xl text-cosmos-glow text-sm font-medium hover:bg-cosmos-glow/30 transition-all flex items-center justify-center gap-2"
            >
              {copiedBuild ? (
                <>
                  <Check className="w-4 h-4" />
                  Copied! Paste into your AI tool
                </>
              ) : (
                <>
                  <Terminal className="w-4 h-4" />
                  Copy build prompt
                </>
              )}
            </button>
          </div>

          {/* Secondary actions */}
          <div className="flex gap-3 pt-4 border-t border-cosmos-border/50">
            <button
              onClick={() => setSummaryDismissed(true)}
              className="flex-1 py-2.5 px-4 border border-cosmos-border rounded-xl text-cosmos-muted text-xs hover:border-cosmos-glow/30 hover:text-cosmos-glow transition-all flex items-center justify-center gap-2"
            >
              <RotateCcw className="w-3.5 h-3.5" />
              Explore tree
            </button>
            <button
              onClick={handleCopySummary}
              className="flex-1 py-2.5 px-4 border border-cosmos-border rounded-xl text-cosmos-muted text-xs hover:border-cosmos-glow/30 hover:text-cosmos-glow transition-all flex items-center justify-center gap-2"
            >
              {copiedSummary ? (
                <>
                  <Check className="w-3.5 h-3.5" />
                  Copied!
                </>
              ) : (
                <>
                  <Clipboard className="w-3.5 h-3.5" />
                  Copy summary
                </>
              )}
            </button>
            <button
              onClick={reset}
              className="py-2.5 px-4 border border-cosmos-border rounded-xl text-cosmos-muted text-xs hover:border-cosmos-conflict/30 hover:text-cosmos-conflict transition-all"
            >
              New goal
            </button>
          </div>

          {/* Closing quote */}
          <div className="mt-6 pt-4 border-t border-cosmos-border/30 text-center">
            <p className="text-xs text-cosmos-muted/50 italic leading-relaxed">
              &ldquo;The AI does the reckoning. You do the judging.&rdquo;
            </p>
            <p className="text-[10px] text-cosmos-muted/30 mt-1">
              &mdash; Inspired by Brian Cantwell Smith
            </p>
          </div>
        </div>
      </motion.div>
    </motion.div>
  );
}
